/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restpay.pages.menu;

import com.restpay.Navigable;

/**
 *
 * @author iyasz
 */
public class CreateMenu extends javax.swing.JPanel {
    
    private Navigable navigator;

    /**
     * Creates new form CreateMenu
     */
    public CreateMenu() {
        initComponents();
    }
    
    public CreateMenu(Navigable navigator) {
        initComponents();
        this.navigator = navigator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filed_menu_name = new javax.swing.JTextField();
        submit_form_menu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        filed_menu_category = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filed_menu_price = new javax.swing.JTextField();
        filed_menu_available = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_upload_image = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        to_menu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 480));
        setPreferredSize(new java.awt.Dimension(1020, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Tambah Menu");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 98, 98));
        jLabel2.setText("Form untuk pengelolaan menu sistem");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(33, 33, 33));
        jLabel3.setText("Image");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));
        add(filed_menu_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, 40));

        submit_form_menu.setBackground(new java.awt.Color(102, 102, 255));
        submit_form_menu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        submit_form_menu.setForeground(new java.awt.Color(255, 255, 255));
        submit_form_menu.setText("Submit");
        submit_form_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_form_menu.addActionListener(this::submit_form_menuActionPerformed);
        add(submit_form_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 100, 40));

        jLabel4.setForeground(new java.awt.Color(33, 33, 33));
        jLabel4.setText("Ketersediaan");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        filed_menu_category.setBackground(new java.awt.Color(254, 254, 254));
        filed_menu_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(filed_menu_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 310, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 410, 130));

        jLabel5.setForeground(new java.awt.Color(33, 33, 33));
        jLabel5.setText("Kategori");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel6.setForeground(new java.awt.Color(33, 33, 33));
        jLabel6.setText("Nama");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        add(filed_menu_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 310, 40));

        filed_menu_available.setBackground(new java.awt.Color(255, 255, 255));
        filed_menu_available.setText("Tersedia");
        filed_menu_available.addActionListener(this::filed_menu_availableActionPerformed);
        add(filed_menu_available, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        jLabel7.setForeground(new java.awt.Color(33, 33, 33));
        jLabel7.setText("Harga");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel8.setForeground(new java.awt.Color(33, 33, 33));
        jLabel8.setText("Preview");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 180, 160));

        btn_upload_image.setBackground(new java.awt.Color(254, 254, 254));
        btn_upload_image.setText("Upload");
        add(btn_upload_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 100, 30));

        jLabel9.setForeground(new java.awt.Color(33, 33, 33));
        jLabel9.setText("Deskripsi");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        to_menu.setBackground(new java.awt.Color(254, 254, 254));
        to_menu.setText("Kembali");
        to_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        to_menu.setPreferredSize(new java.awt.Dimension(72, 21));
        to_menu.addActionListener(this::to_menuActionPerformed);
        add(to_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void submit_form_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_form_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_form_menuActionPerformed

    private void filed_menu_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filed_menu_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filed_menu_availableActionPerformed

    private void to_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_menuActionPerformed
        if (navigator != null) {
            navigator.navigateTo("MENU");
        }
    }//GEN-LAST:event_to_menuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_upload_image;
    private javax.swing.JCheckBox filed_menu_available;
    private javax.swing.JComboBox<String> filed_menu_category;
    private javax.swing.JTextField filed_menu_name;
    private javax.swing.JTextField filed_menu_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton submit_form_menu;
    private javax.swing.JButton to_menu;
    // End of variables declaration//GEN-END:variables
}
