/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restpay.pages.menu;

import com.restpay.Navigable;
import com.restpay.Refreshable;
import com.restpay.components.ProductCard;
import com.restpay.models.Product;
import com.restpay.repositories.ProductRepository;
import com.restpay.utils.WrapLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author iyasz
 */
public class Menu extends javax.swing.JPanel implements Refreshable {
    
    private Navigable navigator;
    private JPanel pnlGrid;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        initGrid();
        loadProducts();
    }
    
    public Menu(Navigable navigator) {
        initComponents();
        this.navigator = navigator;
        initGrid();
        loadProducts();
    }
    
    private void initGrid() {
        // Setup panel grid dengan WrapLayout
        pnlGrid = new JPanel(new WrapLayout(WrapLayout.LEFT, 16, 16));
        pnlGrid.setBackground(new Color(245, 245, 245));

        // Masukkan ke scrollPane yang ada di designer
        scrollPane.setViewportView(pnlGrid);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    @Override
    public void refresh() {
        loadProducts(); // loadProducts tetap private, dipanggil dari sini ✅
    }
    
    private void loadProducts() {
        pnlGrid.removeAll();

        List<Product> products = ProductRepository.getAll();

        if (products.isEmpty()) {
            JLabel lblEmpty = new JLabel("Belum ada produk");
            lblEmpty.setForeground(new Color(150, 150, 150));
            pnlGrid.add(lblEmpty);
        } else {
            for (Product product : products) {
                pnlGrid.add(new ProductCard(product));
            }
        }

        pnlGrid.revalidate();
        pnlGrid.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        to_createMenu = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Kelola Menu");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 98, 98));
        jLabel2.setText("Form untuk pengelolaan menu sistem");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        to_createMenu.setBackground(new java.awt.Color(102, 102, 255));
        to_createMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        to_createMenu.setForeground(new java.awt.Color(255, 255, 255));
        to_createMenu.setText("Tambah");
        to_createMenu.setBorder(null);
        to_createMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        to_createMenu.addActionListener(this::to_createMenuActionPerformed);
        add(to_createMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 160, 50));
        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 960, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void to_createMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_createMenuActionPerformed
        if (navigator != null) {
            navigator.navigateTo("CREATE_MENU");
        }
    }//GEN-LAST:event_to_createMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton to_createMenu;
    // End of variables declaration//GEN-END:variables
}
